# Generated by Django 4.1 on 2022-09-28 09:05

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Discount", max_length=100)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("FLAT", "FLAT"), ("PERCENT", "Percentage")],
                        max_length=10,
                    ),
                ),
                ("discount_amount", models.IntegerField(default=0, null=True)),
                (
                    "discount_percentage",
                    models.IntegerField(
                        default=0,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(99),
                        ],
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        default=datetime.datetime(2022, 9, 28, 15, 5, 48, 778820)
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        default=datetime.datetime(2022, 9, 28, 15, 5, 48, 778820)
                    ),
                ),
                (
                    "discount_category",
                    models.CharField(
                        choices=[("DATE", "DATEWISE"), ("TIME", "TIMEWISE")],
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateField(default=datetime.date.today)),
                ("end_date", models.DateField(default=datetime.date.today)),
                ("Is_Valid", models.BooleanField(default=False)),
            ],
        ),
    ]
